Repository ardeois/graphql-codegen-typescript-mock-data, pull requests merged in 2020-07, with the labels that each got.

#21 feat: add `scalars` config option for custom GraphQL [scalar -> casual] mappings
  README.md
  src/index.ts
  tests/__snapshots__/typescript-mock-data.spec.ts.snap
  tests/typescript-mock-data.spec.ts
Labels: minor

#26 feat: use `indefinite` to find the correct article
  package.json
  src/index.ts
  tests/__snapshots__/typescript-mock-data.spec.ts.snap
  yarn.lock
Labels: major

#27 doc: update mock name
  README.md
Labels: skip-release
