Repository ardeois/graphql-codegen-typescript-mock-data, pull requests merged in 2022-03, with the labels that each got.

#75 fix: never preserve underscores for enum values
  src/index.ts
  tests/__snapshots__/typescript-mock-data.spec.ts.snap
  tests/typescript-mock-data.spec.ts
Labels: patch

#76 fix: update dependencies
  package.json
  yarn.lock
Labels: patch

#77 fix: relationshipsToOmit bug when terminateCircularRelationships is true
  src/index.ts
  tests/__snapshots__/typescript-mock-data.spec.ts.snap
  tests/circular-mocks/create-mocks.ts
  tests/circular-mocks/spec.ts
  tests/circular-mocks/types.ts
  tests/typescript-mock-data.spec.ts
Labels: minor

#78 feat: relationshipsToOmit bug when terminateCircularRelationships is true
  src/index.ts
  tests/__snapshots__/typescript-mock-data.spec.ts.snap
  tests/circular-mocks/create-mocks.ts
  tests/circular-mocks/spec.ts
  tests/circular-mocks/types.ts
  tests/typescript-mock-data.spec.ts
Labels: minor

#79 fix: add stale bot
  .github/stale.yml
Labels: skip-release
